"""Generate engine/cpu/opcodes.h from dsl/opcodes.py. Run after editing opcodes."""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dsl.opcodes import (  # noqa: E402
    CTX, MAX_STACK, OPCODES, SERIES,
    SK_EMA, SK_PREV2, SK_RAW, SK_RING, SK_WILDER1, SK_WILDER2,
)

HEADER = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "engine", "cpu", "opcodes.h")


def main() -> None:
    lines = [
        "// GENERATED by dsl/gen_opcodes.py -- do not edit.",
        "#pragma once",
        "",
        "enum Op {",
    ]
    for i, name in enumerate(OPCODES):
        lines.append(f"    OP_{name} = {i},")
    lines.append("};")
    lines.append("")
    for name, val in [("SK_EMA", SK_EMA), ("SK_WILDER1", SK_WILDER1),
                      ("SK_WILDER2", SK_WILDER2), ("SK_RING", SK_RING),
                      ("SK_PREV2", SK_PREV2), ("SK_RAW", SK_RAW),
                      ("VM_MAX_STACK", MAX_STACK), ("VM_N_CTX", len(CTX))]:
        lines.append(f"#define {name} {val}")
    lines.append("")
    lines.append("// series: " + ", ".join(f"{k}={v}" for k, v in SERIES.items()))
    lines.append("// ctx: " + ", ".join(f"{k}={v}" for k, v in CTX.items()))
    lines.append("")
    with open(HEADER, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
