// GENERATED by dsl/gen_opcodes.py -- do not edit.
#pragma once

enum Op {
    OP_PUSH_CONST = 0,
    OP_PUSH_PARAM = 1,
    OP_PUSH_SERIES = 2,
    OP_PUSH_SERIES_LAG = 3,
    OP_PUSH_CTX = 4,
    OP_LOAD = 5,
    OP_STORE = 6,
    OP_ADD = 7,
    OP_SUB = 8,
    OP_MUL = 9,
    OP_DIV = 10,
    OP_NEG = 11,
    OP_ABS = 12,
    OP_MIN2 = 13,
    OP_MAX2 = 14,
    OP_SQRT = 15,
    OP_LOG = 16,
    OP_GT = 17,
    OP_LT = 18,
    OP_GE = 19,
    OP_LE = 20,
    OP_EQ = 21,
    OP_NE = 22,
    OP_AND = 23,
    OP_OR = 24,
    OP_NOT = 25,
    OP_SMA = 26,
    OP_EMA = 27,
    OP_RSI = 28,
    OP_ATR = 29,
    OP_HIGHEST = 30,
    OP_LOWEST = 31,
    OP_STDDEV = 32,
    OP_DELAY = 33,
    OP_CROSSOVER = 34,
    OP_CROSSUNDER = 35,
    OP_SMA_RAW = 36,
    OP_HIGHEST_RAW = 37,
    OP_LOWEST_RAW = 38,
    OP_STDDEV_RAW = 39,
    OP_DELAY_RAW = 40,
    OP_SIG_EL = 41,
    OP_SIG_XL = 42,
    OP_SIG_ES = 43,
    OP_SIG_XS = 44,
    OP_SET_STOP = 45,
    OP_SET_TP = 46,
    OP_SET_TRAIL = 47,
    OP_SET_SIZE = 48,
    OP_HALT = 49,
};

#define SK_EMA 0
#define SK_WILDER1 1
#define SK_WILDER2 2
#define SK_RING 3
#define SK_PREV2 4
#define SK_RAW 5
#define VM_MAX_STACK 32
#define VM_N_CTX 5

// series: open=0, high=1, low=2, close=3, volume=4
// ctx: bar_index=0, position=1, entry_price=2, equity=3, bars_held=4
